// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_info.sql

package sqlcgen

import (
	"context"
	"time"
)

const serverInfo = `-- name: ServerInfo :one
SELECT now()::timestamptz AS now, postgis_version() AS postgis_version
`

type ServerInfoRow struct {
	Now            time.Time
	PostgisVersion interface{}
}

func (q *Queries) ServerInfo(ctx context.Context) (ServerInfoRow, error) {
	row := q.db.QueryRow(ctx, serverInfo)
	var i ServerInfoRow
	err := row.Scan(&i.Now, &i.PostgisVersion)
	return i, err
}
